### ISSUE TITLE
what function is called once file is uploaded?

### ISSUE THREAD

**Issue by RonenAzachi** [ptkach/fileDroppa#31]

**Comment by Antyneskul** [comment]
What variant of importing to main App do you use - fileDropZone or fileDroppa ?

**Comment by RonenAzachi** [comment]
fileDroppa , i want the response from the upload.

**Comment by Antyneskul** [comment]
I've check and found that this functionality was not implemented.
I'll create pull request.
Also your ideas are welcome.

**Comment by RonenAzachi** [comment]
thanks ! waiting...

**Comment by ptkach** [comment]
Hi,

Actually there's a callback which you can use:

`import {Component, EventEmitter} from 'angular2/core';
import {FileDroppa} from "../components/Directives/FileDroppa";

@Component({
    selector: 'my-app',
    directives: [FileDroppa],
    template: `<div fileDroppa
                (notifyFilesUpdated)="notifyFilesUpdated($event)">
                Drop files here or click to select
            </div>`
})
export class AppComponent {
    constructor() {
    }

    notifyFilesUpdated(files) {
        console.log(arguments);
    }

}`

**Comment by RonenAzachi** [comment]
i am also using FileDropZone.
Thanks, as when i am uploading an image with autoload, i want to parse the response and show the result for this image.

**Comment by Antyneskul** [comment]
So you want to get a response from the server as one of params for callback?

**Comment by RonenAzachi** [comment]
yes

**Comment by ptkach** [comment]
Response and file now comes to callback. Check out demo app.component and let me know if that's what you were looking for

**Comment by RonenAzachi** [comment]
hi just implemented, fileUploaded is not being called after upload. pls have a look

/*
 * Angular 2 decorators and services
 */
import {Component, EventEmitter} from 'angular2/core';
import {RouteConfig, Router, ROUTER_DIRECTIVES} from 'angular2/router';
import {FORM_PROVIDERS} from 'angular2/common';
import {FileDropZone} from 'file-droppa';
import {RouterActive} from './directives/router-active';
import {Home} from './home/home';

/*
 * App Component
 * Top Level Component
 */
@Component({
  selector: 'app',
  providers: [ ...FORM_PROVIDERS ],
  directives: [ ...ROUTER_DIRECTIVES, RouterActive,FileDropZone ],
  pipes: [],
  styles: [`
    nav ul {
      display: inline;
      list-style-type: none;
      margin: 0;
      padding: 0;
      width: 60px;
    }
    nav li {
      display: inline;
    }
    nav li.active {
      background-color: lightgray;
    }
  `],
  template: `
    <header>
      <nav>
        <h1>Hello {{ name }} aaaa</h1>
        <ul>
          <li router-active>
            <a [routerLink]=" ['Index'] ">Index</a>
          </li>
          <li router-active>
            <a [routerLink]=" ['Home'] ">Home</a>
          </li>
          <li router-active>
            <a [routerLink]=" ['About'] ">About</a>
          </li>
        </ul>
      </nav>
    </header>
    <fileDropZone
                    [config]="fileDroppaConfig"
                    (filesUpdated)="filesUpdated($event)"
                    (fileUploaded)="fileUploaded($event)"
                    >
               </fileDropZone>


    <main>
      <router-outlet></router-outlet>
    </main>

  
  `
})
@RouteConfig([
  { path: '/', component: Home, name: 'Index' },
  { path: '/home', component: Home, name: 'Home' },
  // Async load a component using Webpack's require with es6-promise-loader and webpack `require`
  { path: '/about', loader: () => require('es6-promise!./about/about')('About'), name: 'About' },
  { path: '/**', redirectTo: ['Index'] }
])
export class App {
  angularclassLogo = 'assets/img/angularclass-avatar.png';
  name = 'Angular 2 Webpack' ;
  url = 'https://twitter.com/AngularClass';
 public uploadFiles = new EventEmitter();

 uploadEvent;
     fileDroppaConfig;

      constructor() {
            this.uploadEvent = new EventEmitter();

            this.fileDroppaConfig = {
                overCls: "customDrop",
                autoUpload: true,
                uploadUrl: "http://0.0.0.0/Server/processImage"
            };
        }

        filesUpdated(files) {
        console.log(files);
        }
        notifyFilesUpdated(files) {
    console.log(arguments);
}


fileUploaded([success, response, file]){
       console.log("uploaded", response, file);
   }



}

**Comment by ptkach** [comment]
It supposed to work. Did you clone my latest changes? Because I didn't update npm package yet

**Comment by ptkach** [comment]
npm package is updated, I checked changes on separate project and it works fine with code from demo app.component. Please double check and let me know

**Comment by RonenAzachi** [comment]
I'll update Sunday. Thanks for doing this so fast.

Cheers

It supposed to work. Did you clone my latest changes? Because I didn't
update npm package yet

—
Reply to this email directly or view it on GitHub
<https://github.com/ptkach/fileDroppa/issues/31#issuecomment-191847716>.

**Comment by ptkach** [comment]
Okay, npm is updated, I close this issue. Feel free to update me on your progress.

**Comment by RonenAzachi** [comment]
working thanks!
