### ISSUE TITLE
Adding headers to configuration

### ISSUE THREAD

**Issue by zcsongor** [ptkach/fileDroppa#33]
It would be nice if one could add headers (for authorization and stuff) to the request.

Nice job anyway, thanks!

**Comment by ptkach** [comment]
Good idea, thank you. 
requestHeaders are now added in config. 

Feel free to check and let me know what you think.

**Comment by zcsongor** [comment]
Great, thanks! Have you thought about more configuration options? Like maxFiles, etc., similar to dropzone options.

**Comment by zcsongor** [comment]
And also would be nice if one could set the 'name' variable in the multipart/form-data.
Now it is always the file's name, and it could confuse the server side.

**Comment by ptkach** [comment]
I was thinking about more configuration options. It's quite easy to add, but I don't have much time now, unfortunately. If you want you can add some extra params in configuration and create PR, it would be very helpful.

And what about file name, I'm planning to provide beforeSend event to make sure user will be able to update information in file object before we send it.

**Comment by zcsongor** [comment]
Sure, will do it. Thanks for this awesome project :)

**Comment by ptkach** [comment]
beforeUpload now added in config and formData can be updated before upload, thanks for the good point!
