### ISSUE TITLE
two dropzones in one view bug

### ISSUE THREAD

**Issue by scsenge** [ptkach/fileDroppa#34]
Hi!

I ran into a problem when I tried to put two dropzones in one view.Even if I binded two different functions for the (fileUploaded) attributes of the dropzones, when I try to upload an image with one of the dropzones, both of the functions are called, so the image will be uploaded  with both of the dropzones to different places.

I would be really grateful if you could help me with this problem,
Csenge

**Comment by ptkach** [comment]
Hi, 

Thank you for reporting. I will fix it in a couple hours

**Comment by ptkach** [comment]
I have fixed it. Please check and let me know if you need something else.
