### ISSUE TITLE
drop - is there a way to change the file before sent to server. 

### ISSUE THREAD

**Issue by ronencamera** [ptkach/fileDroppa#38]
i would like to resize the image, if necessary .

**Comment by ptkach** [comment]
Thank you, good point. 
You can use beforeUpload for that, now it can return Promise, so you can do any async changes with this file. 
As long as you return FromData like object it will be fine.

**Comment by ronencamera** [comment]
thanks for the reply.

I looked into that, but if i want in my case to resize the image before upload. It can not be an async.

**Comment by ronencamera** [comment]
using promise causes an error.

?d41d:73 EXCEPTION: Error during evaluation of "fileUploaded"BrowserDomAdapter.logError @ ?d41d:73BrowserDomAdapter.logGroup @ ?d41d:84ExceptionHandler.call @ ?d41d:49(anonymous function) @ ?d41d:258schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM74993:166SafeSubscriber.next @ VM74993:115Subscriber._next @ VM74993:74Subscriber.next @ VM74993:51Subject._finalNext @ VM74988:124Subject._next @ VM74988:116Subject.next @ VM74988:73EventEmitter.emit @ ?d41d:113NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ?d41d:134NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:88ZoneDelegate.handleError @ zone.ts?949c:703NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:87ZoneDelegate.handleError @ zone.ts?949c:703Zone.runTask @ zone.ts?949c:579ZoneTask.invoke @ zone.ts?949c:809
?d41d:73 ORIGINAL EXCEPTION: SyntaxError: Unexpected end of inputBrowserDomAdapter.logError @ ?d41d:73ExceptionHandler.call @ ?d41d:61(anonymous function) @ ?d41d:258schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM74993:166SafeSubscriber.next @ VM74993:115Subscriber._next @ VM74993:74Subscriber.next @ VM74993:51Subject._finalNext @ VM74988:124Subject._next @ VM74988:116Subject.next @ VM74988:73EventEmitter.emit @ ?d41d:113NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ?d41d:134NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:88ZoneDelegate.handleError @ zone.ts?949c:703NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:87ZoneDelegate.handleError @ zone.ts?949c:703Zone.runTask @ zone.ts?949c:579ZoneTask.invoke @ zone.ts?949c:809
?d41d:73 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ ?d41d:73ExceptionHandler.call @ ?d41d:65(anonymous function) @ ?d41d:258schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM74993:166SafeSubscriber.next @ VM74993:115Subscriber._next @ VM74993:74Subscriber.next @ VM74993:51Subject._finalNext @ VM74988:124Subject._next @ VM74988:116Subject.next @ VM74988:73EventEmitter.emit @ ?d41d:113NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ?d41d:134NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:88ZoneDelegate.handleError @ zone.ts?949c:703NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:87ZoneDelegate.handleError @ zone.ts?949c:703Zone.runTask @ zone.ts?949c:579ZoneTask.invoke @ zone.ts?949c:809
?d41d:73 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at App.fileUploaded (eval at <anonymous> (http://localhost:3000/main.bundle.js:86:2), <anonymous>:168:24)
    at AbstractChangeDetector.ChangeDetector_App_0.handleEventInternal (viewFactory_App:64:31)
    at AbstractChangeDetector.handleEvent (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:660:2), <anonymous>:57:29)
    at AbstractChangeDetector.eval (viewFactory_App:92:111)
    at eval (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:48:2), <anonymous>:121:110)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1783:2), <anonymous>:204:37)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1191:2), <anonymous>:35:41)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1783:2), <anonymous>:203:42)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1191:2), <anonymous>:35:41)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1783:2), <anonymous>:203:42)
    at Zone.runTask (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1783:2), <anonymous>:103:47)
    at ZoneTask.invoke (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1783:2), <anonymous>:271:33)BrowserDomAdapter.logError @ ?d41d:73ExceptionHandler.call @ ?d41d:66(anonymous function) @ ?d41d:258schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM74993:166SafeSubscriber.next @ VM74993:115Subscriber._next @ VM74993:74Subscriber.next @ VM74993:51Subject._finalNext @ VM74988:124Subject._next @ VM74988:116Subject.next @ VM74988:73EventEmitter.emit @ ?d41d:113NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ?d41d:134NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:88ZoneDelegate.handleError @ zone.ts?949c:703NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:87ZoneDelegate.handleError @ zone.ts?949c:703Zone.runTask @ zone.ts?949c:579ZoneTask.invoke @ zone.ts?949c:809
?d41d:73 ERROR CONTEXT:

**Comment by ptkach** [comment]
I have tested it with it and it works great:
```
beforeUpload(file){
        return new Promise((res, rej)=>{
           setTimeout(()=>{
               res(["nameYouLike", file]);
           },1000)
        });
        //return ["nameYouLike", file];
    }
```
This method accepts file (HTML5 File Api interface) and return FormData parameters https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData. Whatever you return in Promise I just add in FormData which will be send

**Comment by ptkach** [comment]
Let me know if that helped and I will close an issue. 
Thank you!

**Comment by ronencamera** [comment]
still getting the error. 

`?d41d:73 EXCEPTION: Error during evaluation of "fileUploaded"BrowserDomAdapter.logError @ ?d41d:73BrowserDomAdapter.logGroup @ ?d41d:84ExceptionHandler.call @ ?d41d:49(anonymous function) @ ?d41d:258schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM80721:166SafeSubscriber.next @ VM80721:115Subscriber._next @ VM80721:74Subscriber.next @ VM80721:51Subject._finalNext @ VM80716:124Subject._next @ VM80716:116Subject.next @ VM80716:73EventEmitter.emit @ ?d41d:113NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ?d41d:134NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:88ZoneDelegate.handleError @ zone.ts?949c:703NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:87ZoneDelegate.handleError @ zone.ts?949c:703Zone.runTask @ zone.ts?949c:579ZoneTask.invoke @ zone.ts?949c:809
?d41d:73 ORIGINAL EXCEPTION: SyntaxError: Unexpected end of input`

`import {Component, Input, EventEmitter, Output} from 'angular2/core';
import {FileDroppa} from 'file-droppa';
import {FilesStore} from 'file-droppa/components/Services/FileStore.service';
import {NgClass} from 'angular2/common';

@Component({
    selector: 'fileDropZone1',
    styles: [`

      .file_droppa_internal {
          border: 3px dashed #DDD;
          border-radius:10px;
          padding:10px;
          width:400px;
          height:100px;
          color:#CCC;
          text-align:center;
          display:table-cell;
          vertical-align:middle;
          cursor:pointer;
      }
      .overlay {
          height: 100%;
          width: 0;
          position: fixed;
          z-index: 1;
          top: 0;
          left: 0;
          background-color: white;
          background-color: rgba(0,0,0, 0.9);
          overflow-x: hidden;
          transition: 0.5s;
      }

    .overlay-content {
        position: relative;
        top: 25%;
        width: 100%;
        text-align: center;
        margin-top: 30px;
        background-color: white;
    }

    .overlay a {
        padding: 8px;
        text-decoration: none;
        font-size: 36px;
        color: #818181;
        display: block;
        transition: 0.3s;
    }

    .overlay a:hover, .overlay a:focus {
        color: #f1f1f1;
    }
    .overlay.full {
      width:100%;
    }
    .dropImagePopup {
      border-radius: 15px;
      border-width: 4px;
      border-style: dashed;
      background-color: #fff;
      color: green;
      background: none;
      border-color: green;
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      margin: 20px;
    }
    .droptarget {
      position: fixed;
      height: 100%;
      width: 100%;
      z-index: 10;
      top:0;
      background-color: rgba(255,255,255,.85);

    }
    .displayNone {
      display: none;
    }
    .centerInfo {
      position: absolute;
      top: 20%;
      left: 0;
      right: 0;
      margin-top: -20px;
    }
    `],
    directives: [FileDroppa,NgClass],
    template: `
    <div class="droptarget" fileDroppa [ngClass]="{displayNone: displayNone}"
        (notifyFilesUpdated)="notifyFilesUpdated($event)"
        [fs]="filesStore">
        <div [hidden]="!visible" class="dropImagePopup">
          <div class="centerInfo">
            <h1>Drop Image To Upload</h1>
            <img src="{{popUpImage}}" width="200px"><br>

            <span>{{popupText}}</span>
          </div>
        </div>
    </div>

    <div fileDroppa [class]="config.customClass"
        (notifyFilesUpdated)="notifyFilesUpdated($event)"
        [fs]="filesStore"
        [overCls]="config.overCls">
        Drag and Drop Images Here
    </div>
    `
})

export class FileDropZone {
  private _config = {
        uploadUrl:null,
        autoUpload:false,
        requestHeaders:{},
        customClass: 'file_droppa_internal',
        beforeUpload: this.beforeUpload
    };
    public uploadFiles = new EventEmitter();
    public removeAllFiles = new EventEmitter();
    public _showButtons:Boolean = false;
    public displayNone: boolean;
    public filesStore:FilesStore = null;
    visible: boolean = false;
    dragged;

    constructor() {
        this.filesStore = new FilesStore();
        this.filesStore.fileUploaded.subscribe(([success, response, file])=>{
            this.notifyFileUploaded(success, response, file)
        })
        this.showUploadOverlay = false;
        this.displayNone = true;
        var that = this;
        this.popUpImage = '';
        document.addEventListener("dragstart", function(event) {

            // Change the opacity of the draggable element
            event.target.style.opacity = "0.4";
        });

        // While dragging the p element, change the color of the output text
        document.addEventListener("drag", function(event) {
      //      document.getElementById("demo").style.color = "red";
        });

        // Output some text when finished dragging the p element and reset the opacity
        document.addEventListener("dragend", function(event) {
        //    document.getElementById("demo").innerHTML = "Finished dragging the p element.";
        //    event.target.style.opacity = "1";


        });


        /* Events fired on the drop target */

        // When the draggable p element enters the droptarget, change the DIVS's border style
        document.addEventListener("dragenter", function(event) {
          that.displayNone = false;
            if ( event.target.className == "droptarget" ) {
                //event.target.style.border = "3px dotted red";
                that.visible = true;

            }
        });

        // By default, data/elements cannot be dropped in other elements. To allow a drop, we must prevent the default handling of the element
        document.addEventListener("dragover", function(event) {
            event.preventDefault();
        });

        // When the draggable p element leaves the droptarget, reset the DIVS's border style
        document.addEventListener("dragleave", function(event) {

            if ( event.target.className == "droptarget" ) {
                event.target.style.border = "";
            //    that.visible = false;
                that.displayNone = true;
            }
        });
    }

    @Input() set config(config) {
        this._config = config ? Object.assign(this._config, config) : this._config;
        this.filesStore.uploadConfig = this._config;
    }

    @Output() filesUpdated:EventEmitter<Array<File>> = new EventEmitter();
    @Output() fileUploaded:EventEmitter<any> = new EventEmitter();

    set showButtons(flag:boolean) {
        this._showButtons = flag;
    }

    get showButtons() {
        return this._showButtons && !this._config["autoUpload"];
    }

    get config() {
        return this._config;
    }

    beforeUpload(file){
            return new Promise((res, rej)=>{
               setTimeout(()=>{
                   res(["nameYouLike", file]);
               },1000)
            });
            //return ["nameYouLike", file];
        }

    upload() {
      console.log('upload');

        this.uploadFiles.emit(true);
    }

    remove() {
        this.removeAllFiles.emit(true);
    }

    notifyFilesUpdated(files:Array<File>) {
      //this.displayNone = true;
      console.log(files);
      var f = files[0];
      var src = '';
      var reader = new FileReader();
      var that = this;
      // Closure to capture the file information.
      reader.onload = (function(theFile) {
        return function(e) {
          // Render thumbnail.
          //console.log(e.target.result);
          that.popUpImage = e.target.result;
        };
      })(f);

      // Read in the image file as a data URL.
      reader.readAsDataURL(f);
      this.popupText = "uploading image";
      console.log('start upload');
    //  this.showUploadOverlay =true;
        this.filesUpdated.emit(files);
      //  this.showButtons = !!files.length;
    }

    notifyFileUploaded(success, response, file){
      console.log('uploaded');
      this.popupText = "upload done, working on image";
      //this.showUploadOverlay =false;
      //this.displayNone = true;
      this.fileUploaded.emit([success, response, file]);


    }


    doneEdit(){
      
      this.displayNone = true;
    }
}


`

**Comment by ronencamera** [comment]
further upload start's with out waiting for the timeout. so i can manipulate the file before.

**Comment by ptkach** [comment]
Hi,
I double checked and timer works fine for me, I reinstalled file-droppa from npm and tested.
Can't tell you for sure but lets try to figure it out. Couple questions:
1) I see you moved config methods from "main" directive/component to fileDropZone1 itself. How config looks where you define him? Can you double check the result of:
`this._config = config ? Object.assign(this._config, config) : this._config;`

Make sure that it beforeUpload has to be there in the way you are expecting.

2) Does it work when you remove promise?
3) Unexpected end of input is too much generic error. Can you please check when it started happening?
4) Does it work the way defined in https://github.com/ptkach/fileDroppa/blob/master/demo/app.component.ts, because for me it works perfectly

Let me know and let's fix it :)

**Comment by ronencamera** [comment]
I think i see the problem, if the config is in the parent. It is calling the function beforeUpload in the parent and not in the component i created.

**Comment by ptkach** [comment]
Yep, I think you are right. Please check and close this issue if it's fine.
Thanks!

**Comment by ronencamera** [comment]
still the upload starts before the 10 second timeout. So how does this help?

beforeUpload(file){
      console.log("before upload");
            return new Promise((res, rej)=>{
               setTimeout(()=>{
                 console.log("after");
                   res(["nameYouLike", file]);
               },10000)
            });
            //return ["nameYouLike", file];
        }

**Comment by ptkach** [comment]
1) before upload
2) after
3) sending

That's my log with your code, where "sending" is xhr.send itself.

**Comment by ronencamera** [comment]
working thanks

**Comment by ptkach** [comment]
As I remember HTML5 File is a subclass of a BLOB and according to https://developer.mozilla.org/en-US/docs/Web/API/FormData/append it should be uploaded successfully and with Base64 it should simply be something like that:

```
var blob = new Blob([content], { type: "image/png,base64"});
formData.append("image", blob);
```

Do you manually create it as Blob with new Blob?

**Comment by ronencamera** [comment]
Yes, blob is created from the canvas. The canvas is used for resizing the image. 


in beforeUpload

blob = dataURItoBlob(canvas.toDataURL("image/jpeg"));
res(["nameYouLike", blob]);

**Comment by ptkach** [comment]
Why do you use dataURItoBlob instead of converting canvas to Blob directly? https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

**Comment by ronencamera** [comment]
for what i understand not support fully on all browsers.

**Comment by ptkach** [comment]
Yes, it's not supported by Safari and Opera yet, but there's quite simple polyfill for that. Can you try it with it?

**Comment by ptkach** [comment]
Please let me know if you fixed your problem and lets close this issue.

**Comment by ronencamera** [comment]
i will give it a try next week. and update. Thanks !
