### ISSUE TITLE
Unexpected directive value 'undefined' on the View of component

### ISSUE THREAD

**Issue by anikets43** [ptkach/fileDroppa#39]
@ptkach 
I'm using angualr beta 12. I'm getting below errors when using filedroppa component inside my component.
Unexpected directive value 'undefined' on the View of component
"browser_adapter.ts:73 EXCEPTION: Error: Uncaught (in promise): Unexpected directive value 'undefined' on the View of component 'FileDropComponent'"

Here's my code
**file-drop.ts**
`import {Component, Input, EventEmitter, Output} from 'angular2/core';
import {FileDroppa, FileDropZone} from 'file-droppa';
import {FilesStore} from 'file-droppa/components/Services/FileStore.service';
import {NgClass} from 'angular2/common';

@Component({
    selector: 'file-dropper',
    directives: [FileDropZone],
    template: `<fileDropZone 
                    [config]="fileDroppaConfig"
                    (filesUpdated)="filesUpdated($event)"
                    (fileUploaded)="fileUploaded($event)"
                    >
               </fileDropZone>`
})
export class FileDropComponent {
    fileDroppaConfig;

    constructor() {
        this.fileDroppaConfig = {
            overCls: "customDrop",
            autoUpload: false,
            uploadUrl: "http://localhost:7584/api/AutoLink/FileUpload",
            beforeUpload: this.beforeUpload
            //requestHeaders:{
            //    'X-Content':'xxx'
            //}
        };
    }

    beforeUpload(file) {
        return new Promise((res, rej) => {
            setTimeout(() => {
                res(["nameYouLike", file]);
            }, 1000)
        });
        //return ["nameYouLike", file];
    }

    fileUploaded([success, response, file]) {
        success && console.log("uploaded - awesome", response, file);
        success || console.log("not uploaded - very bad", response, file);
    }

    filesUpdated(files) {
        console.log("added", files)
    }

}`

**my-component.ts**

`import {FileDropComponent} from '../../components/drop-file/drop-file'

directives: [FileDropComponent],`

**my-component.html**

`<div class="row">
    <file-dropper></file-dropper>
</div>`

Kindly let me know where I'm going wrong

Thanks,
Aniket

**Comment by ptkach** [comment]
Hi Aniket,

Thank you for using file-droppa component and reporting issue. 
At the first glance it looks well. I created empty project with Angular2 beta 13 and put your code there and it works perfectly. 

Can't tell you for sure, but can you carefully double check all the brackets and '' in your code? For example: 

`template: <fileDropZone [config]="fileDroppaConfig" (filesUpdated)="filesUpdated($event)" (fileUploaded)="fileUploaded($event)" > </fileDropZone>`

needs to be:

`template: '<fileDropZone [config]="fileDroppaConfig" (filesUpdated)="filesUpdated($event)" (fileUploaded)="fileUploaded($event)" > </fileDropZone>'`

So double check and let me know

Best Regards, 
Pavlo

**Comment by anikets43** [comment]
Hi @ptkach Appreciate your immediate reply.
I crossed checked for any syntactical error but everything looks good to me. I have created a sample to reproduce the issue. Kindly let me know the issue.

Sample Download Link [https://netorg505347-my.sharepoint.com/personal/aniket_agrawal_asipsolutions_com/_layouts/15/guestaccess.aspx?guestaccesstoken=HxM2iQCGUEjBQzKN2pVa%2fxYRTzF6XuLGeTux31IXnyk%3d&docid=1c0309dbb27514ec2b44f6b28f244be6d](url)

Regards,
Aniket

**Comment by anikets43** [comment]
Copy link and paste to other tab. It will download the sample.
Thanks

**Comment by anikets43** [comment]
Finally it worked for me :). I was missing export statements defined in index.ts. 
Does it provide asyn uploads after dropping and showing the progress of individual files? I want to avoid Upload All click, it should happen just after dropping the files.

Thanks @ptkach for all your help.

**Comment by ptkach** [comment]
I'm glad you found the problem. 
You can set autoUpload to true in config and any file dropped will be automatically uploaded.
Closing this issue, since there's nothing to fix in file-droppa.
