### ISSUE TITLE
Figure out the way to let initialize file upload to server

### ISSUE THREAD

**Issue by ptkach** [ptkach/fileDroppa#4]
Get some button or hotkey which will init file uploading. Because currently whatever you drop gets automatically uploaded.

**Comment by ptkach** [comment]
Implemented idea, looks good to me. @Antyneskul please take a look and let me know what do you think about it.

**Comment by Antyneskul** [comment]
I think it's better to provide one config(options) parameter instead every separated parameter.
In future it can cause unnecessary grows of directive template.

I think it should be like <div fileDroppa [options="'{}'"]>
In this case user can provide this object even from hi own component.

````
{
  options: {
    uploadUrl: '.....',
    overCls: '....',
    ......
  }
}
````

**Comment by ptkach** [comment]
Looks like we will stick to current approach
