### ISSUE TITLE
Import statements

### ISSUE THREAD

**Issue by balajijana** [ptkach/fileDroppa#43]
Hi,

I want to know which of the below import statement is correct or not:
Import 1:
import {Component, Input, EventEmitter, Output} from 'angular2/core';
import {FileDroppa} from 'file-droppa';
import {FilesStore} from 'file-droppa/components/Services/FileStore.service';
import {NgClass} from 'angular2/common';

Import 2:
import {FileDropZone} from 'file-droppa';
import {FilesStore} from 'file-droppa/components/Services/FileStore.service';

Also if i have installed and run the module i am facing the following error:
uncaught exception: uncaught exception: uncaught exception: SyntaxError: expected expression, got '<'
	Evaluating http://localhost:3001/node_modules/file-droppa.js
Please let me know how to resolve this issue

**Comment by ptkach** [comment]
Hi,

it depends on what you are looking for. As it says in readme you can use file-droppa with all logic - droppable area with styles, and file-list (Case 1). Or you can use just area with JS logic. In this case you will need to style it by yourself and create file list by yourself with (notifyFilesUpdated)="notifyFilesUpdated($event)" (Case 2)

Case 1 - import {FileDropZone} from 'file-droppa';
Case 2 - import {FileDroppa} from 'file-droppa';

Issue you described is too generic in Angular2 and it happens sometimes with wrong TypeScript compile config or System.js config. No one else has not reported this issue and I also do not observe it. 

Please douple check your configs.
