### ISSUE TITLE
Clear the files list after uploaded

### ISSUE THREAD

**Issue by anikets43** [ptkach/fileDroppa#44]
@ptkach 
I am using autoUpload, how do I clear the file list inside fileUploaded event.

` fileUploaded([success, response, file]) {
        console.log('Done Upload')
        success && console.log("uploaded - awesome", response, file);
        success || console.log("not uploaded - very bad", response, file);
    }`

Also I want to customize the files list something like gmail. Is that possible with custom styles.

Please suggest.

Much Regards,
Aniket

**Comment by ptkach** [comment]
With autoUpload equals true fileList is cleared automatically for you.
If you want to customize file list you would need to use FileDroppa directive and customize it by yourself:
`directives: [FileDroppa],`

It will give you area with no styles but all JS logic applies. Using:

`(notifyFilesUpdated)="notifyFilesUpdated($event)`

you will get whole list of files you can use in HTML5 File format which you can pass to another component.

Here's example:

```
import {FileDroppa} from 'file-droppa';

@Component({
    selector: 'hello-app',
    directives: [FileDroppa],
    template: `
            <div fileDroppa (notifyFilesUpdated)="notifyFilesUpdated($event)">
                Any Text or content you want
            </div> `
})
export class HelloApp {
    notifyFilesUpdated(...arg){
        console.log(arg);
        //call some service with files
    }
}
```

Don't forget to add your styles to div! Good luck.

**Comment by anikets43** [comment]
Hi @ptkach 
i am getting below errors before it comes to fileUploaded([success, response, file]){}. Also, I am getting success = false from the server even though I am returning Json(true) after successful upload. 
Note: Using .NET Core at the back end.

That could be the reason it's not clearing the file list after uploading. Could you please tell me what should I return from the server on upload success. How to avoid below errors.

![error](https://cloud.githubusercontent.com/assets/7136799/14361103/f76e0d82-fd16-11e5-8cef-3219461da311.png)

**Comment by ptkach** [comment]
Hi,

Oh, I see. That's pretty easy. It happens because you have Failed Request which as I see happens because Chrome CORS policy. Please refer to it and it should be fine: http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

Best Regards, 
Pavlo
