### ISSUE TITLE
Can't bind to 'config' 

### ISSUE THREAD

**Issue by balajijana** [ptkach/fileDroppa#45]
Hi,

I am getting a issue like this when i am using the file-droppa module:

Can't bind to 'config' since it isn't a known native property ("xs="row"><md-input-container flex-gt-xs="" class="md-block"><label>File Upload</label><filedropzone [ERROR ->][config]="fileDroppaConfig" (filesupdated)="filesUpdated($event)" (fileuploaded)="fileUploaded($event")

Please help me to resolve it

**Comment by ptkach** [comment]
I don't understand what exactly are you doing? Please provide more detailed explanation. Also revisit Readme for example of working workflow, it's tested and used by bunch of developers

**Comment by balajijana** [comment]
Hi,

Its working now! Now i got the drop area

initially it was:

filedropzone([config] = 'fileDroppaConfig', (filesupdated) = 'filesUpdated($event)', (fileuploaded) = 'fileUploaded($event)')

I have changed it to: 

fileDropZone([config] = 'fileDroppaConfig', (filesupdated) = 'filesUpdated($event)', (fileuploaded) = 'fileUploaded($event)')

Thanks for your help

**Comment by ptkach** [comment]
You are welcome!
