### ISSUE TITLE
File upload -regd

### ISSUE THREAD

**Issue by balajijana** [ptkach/fileDroppa#46]
Hi,

I have a doubt regarding the file upload. when i click on the drop-area to select the file its working perfectly. I am able to choose the image and once i click on the upload files button, it gets uploaded and disappears. how can i get the uploaded image URL in the response?..please give me an idea

Thanks
Balaji

**Comment by ptkach** [comment]
Hi,
Server is responsible for response. Tune your server to send it back, or make another get request after it's saved to retrieve it.

**Comment by balajijana** [comment]
Thanks for your response
