### ISSUE TITLE
How do I actually use this?

### ISSUE THREAD

**Issue by fxck** [ptkach/fileDroppa#47]
Where do I import `FileDropZone` or `FileDroppa` from? Certainly not from `'./FileDroppa'` and definitely not from https://github.com/ptkach/fileDroppa/blob/master/demo/app.component.ts#L2 either. Am I like supposed to.. install it with npm, c&p it to my project and build it myself? Or am I missing something?

**Comment by fxck** [comment]
I see, it's `import { FileDroppa } from 'file-droppa';`

**Comment by ptkach** [comment]
Hi,

You can also use:

`import {FileDropZone} from 'file-droppa';`

It's gonna give you droppable area with file list.
