### ISSUE TITLE
max file size and max number of files options

### ISSUE THREAD

**Issue by devilsuraj** [ptkach/fileDroppa#50]
is there any option to limit the number of files and size of the file , also the extensions? which event is fired when new file is added i am not able to figure it out ..

**Comment by ptkach** [comment]
Hi, event is filesUpdated. Take a look in Readme. It always get the list of all files uploaded, but there's no filter by length or size. I think it makes sense to add it.

**Comment by devilsuraj** [comment]
in fileupdated i can do  =>   if (files.length > 3) {//do something} but how can i get the current file which was added so i can remove it or either give a different style?

**Comment by ptkach** [comment]
As I said fileUploaded gives list of all files that are added via dropzone or file input. But it's read only. 
BTW, you can use different directive -            
```
 <div fileDroppa (notifyFilesUpdated)="notifyFilesUpdated($event)">
                Any Text or content you want
            </div> 
```

You will be able to build your own file list.
But if you wait I will add fileUpdated ability to modify files tomorrow or on Monday.

**Comment by devilsuraj** [comment]
thanks for the hint i will give it a try and also will wait for your solution too, it will be great with those filters .  my project going to take a week more so not in hurry can implement that at anytime . its  a great module you have developed , will contribute something if time permits :) ............ have one more issue too (dont know whether this functionality is available or not ) on file upload it vanishes file-list , it should show which files uploaded successfully and which not and thumbnails should remain there with respective css (success/error) . and if it can get images (already uploaded) from server and display on dropbox then it will be a fully loaded module just suggestion .

**Comment by ptkach** [comment]
Hi, I've added validateFile function which will let you validate any file dropped or selected. Please check.
