### ISSUE TITLE
File type validation

### ISSUE THREAD

**Issue by vimalavinisha** [ptkach/fileDroppa#52]
Hi,
      Please help me to validate file type in filedropa
I need to allow users to upload only .jpeg,.png,.jpeg,.gif file type images
Here is my code.
I could not see the whethere validateFile  function is called or not

 this.fileDroppaConfig = {
                 autoUpload: false,//**Optional**
                 uploadUrl: '',
                 validateFile: this.validateFile,//This function will receive each dropped or selected file
             };
  validateFile(file) {
         //You can provide any file validation you want here. File size, type, etc...
         console.log('file validate',file);
     }

**Comment by ptkach** [comment]
Hi,

Do you say that your console.log is not called when you drop something in drop area? 

Because validateFile supposed to get file (HTML5 File object) and you can simply based on file.type with regular expression return true if valid or false if not

**Comment by vimalavinisha** [comment]
Yes when will validateFile function invoke? yes i can do file.type with regular expression validation if validateFile invoke? Even my console.log is not called when i drop something in drop area...
Please clarify

**Comment by ptkach** [comment]
Hi @vimalavinisha,

Sorry for not answering very fast. I just double checked with last version in npm and I see that, validateFile function works as expected and is called once you drop or select file. 

To summaraize: once you drop or select file validateFile function is called and expect you to return true to procceed with this file or false - to skip it and not consider.
