### ISSUE TITLE
No Directive annotation found on FileDroppa

### ISSUE THREAD

**Issue by enlightendev** [ptkach/fileDroppa#54]
Getting a no directive annotation found error. Probably something to do with angular2 rc1?

`import FileDroppa from 'file-droppa'
import { Component } from '@angular/core';

@Component({
    directives: [FileDroppa],
    templateUrl: 'app/components/upload/upload.component.html'
})
export class UploadComponent {
    
}`

# Template
`<section class="content">

        <div class="row">

            <fileDroppa [url]="'http://localhost:8080/api/document/upload'">

            </fileDroppa>

        </div>

    </section>
`

<img width="1251" alt="screen shot 2016-06-23 at 5 42 05 pm" src="https://cloud.githubusercontent.com/assets/570067/16321248/e2e73962-3969-11e6-8956-9629e5f27230.png">

**Comment by enlightendev** [comment]
package.json 
"dependencies": {
    "@angular/common": "^2.0.0-rc.1",
    "@angular/compiler": "^2.0.0-rc.1",
    "@angular/core": "^2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "^2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "@angular/router-deprecated": "^2.0.0-rc.1",
    "angular2-jwt": "^0.1.16",
    "angular2-uuid": "^1.0.7",
    "bootstrap": "^3.3.6",
    "core-js": "^2.2.2",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "file-droppa": "^0.9.2",
    "font-awesome": "^4.5.0",
    "immutable": "^3.7.6",
    "jquery": "^2.2.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "^5.0.0-beta.6",
    "systemjs": "0.19.6",
    "zone.js": "^0.6.12"
  },

**Comment by ptkach** [comment]
Hi @enlightendev,

Thanks for reporting, but I'm totally confused because it looks perfectly well. I've created separate project with the same configuration you have (rc1) and copy-pasted your code and it works like a charm.

The only one difference is System.js, I believe that system.js configuration is place you will need to fix. Please let me know how it goes.

Thanks,
Pasha

**Comment by enlightendev** [comment]
Hey @ptkach 

So i tried with a fresh project and got the same result. I used angular2-seed (https://github.com/angular/angular2-seed) starter with webpack.

Here is the project to reproduce the error https://github.com/enlightendev/file-droppa-tmp.

When up and running go to http://localhost:3000/#/upload to see error.

Thanks
Juan

**Comment by ptkach** [comment]
Hi @enlightendev,

Thank you for your feedback. It was very useful. I don't know what exactly caused it, but after hours of investigation I updated my lib to rc3 and published with update and it fixed problem in your example. 

Please try and let me know.

**Comment by enlightendev** [comment]
I tried, same issue. I updated package.json to "file-droppa": "^0.9.4",

npm prune
npm install

I updated my repo with this change. Did you try with my repo?

**Comment by ptkach** [comment]
Check out this fork - https://github.com/ptkach/file-droppa-tmp, it works perfectly well there. Here's the screenshot:

<img width="447" alt="screen shot 2016-06-24 at 5 39 40 pm" src="https://cloud.githubusercontent.com/assets/3469726/16351577/ad28d7ba-3a34-11e6-8ab3-b1bd41f5d521.png">

**Comment by enlightendev** [comment]
Looks good. I cant understand what the problem with the initial project was. Thanks for your help. Hopefully I was able to help improve the great work you already did.

Juan
