### ISSUE TITLE
filesUpdated function is not calling while after pick image from droppa area. 

### ISSUE THREAD

**Issue by Muthu2020** [ptkach/fileDroppa#56]
Hi,
(filesUpdated)	-> " Callback which will be fired once any file was added or removed with state of files after update"
But filesUpdated function only calls when i click remove button.

here is my code:
HTML:
fileDroppa((filesUpdated)="filesUpdated($event)")
Component:

 filesUpdated(files) {
    console.log('Store state updated! Current state: ', files);
    this.myfile = files;
    console.log('fiel',this.myfile);
  }

**Comment by ptkach** [comment]
Hi @Muthu2020,

Make sure you're using example from Readme. It works perfectly well with it:

<img width="465" alt="screen shot 2016-07-01 at 9 26 49 am" src="https://cloud.githubusercontent.com/assets/3469726/16522839/1b087310-3f6e-11e6-93e8-228bf63f9bb2.png">
