### ISSUE TITLE
Is there a way to apply styles to custom template

### ISSUE THREAD

**Issue by shadeeka** [ptkach/fileDroppa#57]
i have used custom template in drop area, it works great, but the thing is i cannot apply styles to any of elements or change look & feel of existing .
can anyone please help, it would be really great when we use this component in different applications

thank you

**Comment by ptkach** [comment]
Hi @shadeeka,

Thank you for reporting, at this moment you can override template and give it some structure with css classes:

`
<fileDroppa [url]="'http://localhost:8080/api/document/upload'"
    (filesUpdated)="filesUpdated($event)"
    [autoUpload]="false"
            **[dropZoneTemplate]="dropZoneTemplate"**
>
</fileDroppa>
...
@Component({
    directives: [FileDroppa],
    templateUrl: './upload.component.html'
})
export class UploadComponent {
  **public dropZoneTemplate = `
      <div class="awesome_override_xxx">Here I'm overriding <span>library template</span></div>
  `;**
  filesUpdated(files) {
      console.log("Store state updated! Current state: ", files)
  }
}`

Then you can just add global css with styles for classes you pass:

`
  <head>
    <meta charset=UTF-8>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Angular2 Seed</title>
    <style>
      .awesome_override_xxx {
        border: 1px solid red;
      }
    </style>
    <base href="/">
  </head>
`

At this moment this is the best option, but I will think how to pass styles to fileDroppa component.

Best Regards,
Pavlo Tkach

**Comment by shadeeka** [comment]
Thank you , I will try this

**Comment by RodEsV** [comment]
it hasn't change ? 
so ... do I change it from  the index.html filel ?
