### ISSUE TITLE
Adding Headers for Bearer Authrorization

### ISSUE THREAD

**Issue by moumoune** [ptkach/fileDroppa#59]
Hi, I try to use this lib to send files on a server with OAuth authentification.

that's what I did:

```typescript
ngOnInit() {
    this.access_token = this.authService.getAccessToken(); 
    console.log('ACCESS_TOKEN ' + this.access_token); // ok here
  }

...

beforeRequest(xhr){
    let bearerToken = "Bearer " + this.access_token; // access_token undefined here :(
    console.info('beforeRequest' + bearerToken);
    xhr.setRequestHeader("Authorization", bearerToken);
    xhr.withCredentials = true;
    console.log(xhr);
  }

```

Any idea on this? How to recover the access token in my component, and transmit it to the callback method?

**Comment by ptkach** [comment]
Hi,

I guess you need to bind before request to correct context of this with bind for example 

Let me know how it goes.
