### ISSUE TITLE
Communication with the backend

### ISSUE THREAD

**Issue by moumoune** [ptkach/fileDroppa#60]
Hi, actually I try to connect this lib with my own backoffice.

It works with this request (do with Postman):

<img width="954" alt="capture d ecran 2016-08-11 a 18 18 14" src="https://cloud.githubusercontent.com/assets/7457308/17596069/098dd542-5ff0-11e6-9bd1-1ccbd70b4ebc.png">

But the request send by fileDroppa is `application/octet-stream`. Any idea how to send file via classic formData. And how the request is build with multiple files ? I can adapt my backend but i don't understand how the data are sent to the back from fileDroppa actually.

**Comment by ptkach** [comment]
Hi,

it's weird because by default fileDroppa sends files as formData. It provides  beforeFileUpload callback which gets formData as parameter. Please see example in Readme.

**Comment by moumoune** [comment]
I see configuration in the Readme, but not an exemple with a simple exemple of the full upload process. Sorry, this is the first time i try to implement this kind of feature :s

**Comment by ptkach** [comment]
I don't really understand what do you mean by full upload process and I would say that example in Readme (at the bottom of the page) is absolutely full.

But let me try help you here:

1) You import fileDroppa and connect it with your component(s) as shown in readme (in your template)
2) You provide it with configuration which described in readme. URL is only one required field, other - optional
3) That's it. It will render the same box as you see in demo and once you drop or select file it uploads it to the given url as formData in post request (BY DEFAULT)

Let me know if it helps

**Comment by moumoune** [comment]
I made myself an example upload with drag'n drop without any lib, and I better understand the process. Thank you for the help; This issue is closed.
