### ISSUE TITLE
Support for rc6?

### ISSUE THREAD

**Issue by johntzan** [ptkach/fileDroppa#61]
Upgraded to rc6, moved the directive to my module, getting template parse errors now where fileDropZone is.

**Comment by ptkach** [comment]
Hi @johntzan,

Thank you for reporting. I will provide support for rc6 of course. You can expect it on Tuesday next week.

**Comment by ptkach** [comment]
Hi @johntzan ,

As I promised I fixed those issues and checked on angular2-seed. I've provided support for rc7, so please make sure you upgrade to rc7 before you install fixed version of file-droppa. When I used angular2-seed rc6 to test my changes it didn't load at all before I updated to angular2-seed to rc7. 

I've not yet pushed those changes to github, but npm is updated. Please reinstall it from there. Gihub I will update tomorrow as well as docs. So please make sure you use it as a module, not Directive:

`

import FileDroppa from 'file-droppa';
@NgModule({
  declarations: [...],
  imports     : [...FileDroppa...],
  providers   : [...]
  bootstrap   : [...]
})

`

**Comment by johntzan** [comment]
Hi @ptkach ,  After upgrading, i'm getting 404 errors from my server pointing to all .js.map files of all .js files. Any idea why? I am using systemjs.config and a node server. 

Failed to parse SourceMap: http://localhost:3000/file-droppa/index.js.map
Failed to parse SourceMap: http://localhost:3000/file-droppa/components/module.js.map
Failed to parse SourceMap: http://localhost:3000/file-droppa/components/Directives/FileDroppa.js.map
Failed to parse SourceMap: http://localhost:3000/file-droppa/components/Services/FileStore.service.js.map
Failed to parse SourceMap: http://localhost:3000/file-droppa/components/Services/FileWrapper.service.js.map
Failed to parse SourceMap: http://localhost:3000/file-droppa/components/Services/FileUpload.service.js.map
Failed to parse SourceMap: http://localhost:3000/file-droppa/components/Directives/File.js.map
Failed to parse SourceMap: http://localhost:3000/file-droppa/components/Directives/FileDropZone.js.map
Failed to parse SourceMap: http://localhost:3000/file-droppa/components/Services/FileParser.service.js.map
Failed to parse SourceMap: http://localhost:3000/file-droppa/components/Directives/FileList.js.map
Failed to parse SourceMap: http://localhost:3000/file-droppa/components/Pipes/GetSize.pipe.js.map

**Comment by ptkach** [comment]
Hi,

Yes, its System.js configuration you have which forces System.js to search for fileName.js.map file whenever it requires fileName.js file. 

Just change your config or use webpack (I absolutely happy using webpack)

**Comment by johntzan** [comment]
ive tried webpack early on and found some difficulties with it, so i guess i need to find a working systemjs config for this, Thanks
