### ISSUE TITLE
Useable without url

### ISSUE THREAD

**Issue by madoar** [ptkach/fileDroppa#66]
I'm thinking about using your library for my application. My problem is, that I don't have a server to whom I wish to upload the dropped files. Instead I want to process the files on the client and send the processed results to a server via a json rest interface.

To do this I need a way to "upload" files without sending them to a server, instead I only want to have a given method called, when the user dropped a file inside the drop zone.
Is this possible with this library?

**Comment by ptkach** [comment]
Hi @madoar ,

Sure you can, just set some mock url and subscribe for beforeAddFile which will give you uploaded file. 

Let me know if this helps
