### ISSUE TITLE
Implement FileDroppa with Firebase Storage

### ISSUE THREAD

**Issue by mkelowna** [ptkach/fileDroppa#67]
I am currently working on an app uploading to Firebase Storage and would like to implement fileDroppa. I know filesUpdated(files) gives me a list of added files when added.  Is there a way to  intercept the upload click event, process the upload to Firebase Storage, and return a response to the user? Thanks.

**Comment by ptkach** [comment]
I would suggest you use beforeFileUpload hook for it. Just put your files to firebase storage and return null to prevent library from sending it. Let me know if it helps
