### ISSUE TITLE
Adding support for ES5

### ISSUE THREAD

**Issue by nefcanto** [ptkach/fileDroppa#68]
This is a feature request.

Can you both include build folder to your package, and also support ES5 through global variables like ng.core and ng.common?

I truly need that, and I would really appreciate that.

Thank you so much.

**Comment by ptkach** [comment]
Hi @nefcanto,

This is not quite frequent requirement and as far as I know not much people use it as a pure ES5 global variable. I would suggest you to clone the repo and update tsconfig compilation options module to UMD then rebuild it and try how it works for you. Let me know if you would need any help with it.
