### ISSUE TITLE
Dynamic URL

### ISSUE THREAD

**Issue by tauciokas** [ptkach/fileDroppa#70]
Hey Guys, 

Filledroppa is brilliant, but is there a way to change url dynamically?

Currently I'm getting an error:

> Unhandled Promise rejection: Template parse errors:
> Parser Error: Got interpolation ({{}}) where expression was expected at column 27 in

`
<fileDroppa
                [url]="'https://api.sample.com/v0/{{galleryId}}/post'"
                [autoUpload]="true"
                [showFilesList]="true"
                [beforeRequest]="beforeRequest"
                [beforeFileUpload]="beforeFileUpload"
                [beforeAddFile]="beforeAddFile"
                (filesUpdated)="filesUpdated($event)"
                (fileUploaded)="fileUploaded($event)">
            </fileDroppa>
`

Component: 

```
export class DropzoneComponent {

    galleryId: string;

    constructor(private _toast: ToastService) {
        this.galleryId = localStorage.getItem('ad_id');
    }
```

Is this something I'm doing wrong?

**Comment by ptkach** [comment]
Hi @tauciokas,

This should actually work. I guess something is wrong with value itself. I would suggest you to check that value is stored in galleryId, try making getter for this field. Let me know if problem still exist

**Comment by tauciokas** [comment]
Even if I change the value to something static i still get this error... Weird :/ At the beginning I thought maybe the gallery ID is not available at the time when filedroppa component runs and undefined is returned but even if I change that to static string, I still get the same error

**Comment by tauciokas** [comment]
Is there a way to manipulate url within the constructor? Rather then using it withing template?

**Comment by ptkach** [comment]
hey @tauciokas,

I see what the problem is. Didn't notice it before, you have to use it this way:

`<fileDroppa [url]="url"></fileDroppa>`

`@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';
  url = 'https://salty-taiga-80701.herokuapp.com/upload';
}
`
