### ISSUE TITLE
Getting BrowserModule has already been loaded.

### ISSUE THREAD

**Issue by sunillokhande** [ptkach/fileDroppa#71]
Hello,
Environmet in use : angular2.
I am using File droppa, and getting the error "BrowserModule has already been loaded", When I import file droppa in chlid module.
I show on your git page it is solved long back. I am getting this error now.
Can you please suggest me what changes i need to do?

Thank You!

**Comment by ptkach** [comment]
hi @sunillokhande , fix for it was released today with new npm version.
