### ISSUE TITLE
How can I add i18n?

### ISSUE THREAD

**Issue by shalugin** [ptkach/fileDroppa#72]
I want to rename text on buttons and in drop zone. What is the simplest way to do it?

**Comment by ptkach** [comment]
Nice catch, there's no such kind of functionality at this moment. I will probably add in next update I'm releasing this weekend.

**Comment by shalugin** [comment]
Probably the best way to do it is custom template. With custom template we can include another UI library, like material.

**Comment by ptkach** [comment]
Hi @shalugin,

I've released new npm package with fix for it. 

<img width="483" alt="screen shot 2017-07-06 at 8 12 06 pm" src="https://user-images.githubusercontent.com/3469726/27937765-7f5c1e60-6287-11e7-80a3-021bde74e8a3.png">

**uploadButtonTemplate** and **removeButtonTemplate**. 

This is the way you can use them:

``
export class AppComponent {
  url = 'http://someurl.com';
  uploadButtonTemplate = `
      <div class="my-custom-cls">
        <span>New Custom Текст :)</span>
       </div>
    `;
}

<fileDroppa [url]="url" `[uploadButtonTemplate]="uploadButtonTemplate"></fileDroppa>`

**Comment by shalugin** [comment]
@ptkach Thank you!

**Comment by shalugin** [comment]
@ptkach `innerHTML` is a good solution, but with `innerHTML` I cannot use custom component, for example material2: `<button md-button md-raised-button color="primary">Загрузить файлы</button>`. Is there any way to do it?

Is this repository actual? GitHub tells 

> Latest commit e37debd on Oct 12, 2016

**Comment by ptkach** [comment]
Hey @shalugin,

Oh, I see what you're saying. I won't probably have time to do it in next few days, so feel free to implement it and contribute. I've pushed latest version so you can easily pick it up.

**Comment by shalugin** [comment]
Looks like it related to https://github.com/angular/angular/issues/12530
