### ISSUE TITLE
Getting formData empty

### ISSUE THREAD

**Issue by sunillokhande** [ptkach/fileDroppa#79]
I checked formData under beforeFileUpload(formData), And I found was an empty. Due to that I was not able to get the file at server backend.
I also checked file is getting added, I checked filesUpdated() where I found the proper file. But still the formData is empty. See the below image:
![emptyformdata](https://user-images.githubusercontent.com/19899275/29201858-d8024daa-7e7f-11e7-8400-9660fb1ca0e7.png)

Is I am doing anything wrong or missing anytihing?

And at server side I am getting file in asp.net : 
```
public ActionResult UploadCustomers([FromBody] HttpPostedFileBase formData)
        {
            var httpPostedFile = System.Web.HttpContext.Current.Request.Files[0];

            return null;
        }
```
Please let me know, the changes to be made

**Comment by ptkach** [comment]
Hi @sunillokhande,

This is the way formData works, it doesn't show it contents like Array or Object. 

<img width="1080" alt="screen shot 2017-08-12 at 2 07 54 pm" src="https://user-images.githubusercontent.com/3469726/29243202-d811b482-7f67-11e7-8d02-6cb318f2df3d.png">
